### ISSUE TITLE
double free or corruption (fasttop) in in receiver() at netmap_plugin/netmap_collector.cpp:213

### ISSUE THREAD

**Issue by bdrung** [pavel-odintsov/fastnetmon#706]
On Debian 9 (stretch) with fastnetmon 1.1.3, I get an assertion error on start due to a double free or corruption (fasttop). The stack trace is:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 140251706722185, 0, 140251706292199, 140251709601280, 3432, 140251709581568, 140251709584448, 94050827506416, 140251706288946, 3472328228581748082, 143, 0, 3432, 0, 140251599963904}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007f8ee51e13fa in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x3030303063313834, sa_sigaction = 0x3030303063313834}, sa_mask = {__val = {3546642316668581677, 3274715270390755939, 3472328296226648109, 3475143045726351408, 2314885530819502128, 2314885530818453536, 2314885530818453536, 8536110337263411232, 7306639832038339169, 3472328305673320500, 3546642316668581677, 3274715270390756451, 3472328296226648184, 3475143045726351408, 2314885530819502128, 140251599959008}}, sa_flags = 97, sa_restorer = 0x7f8edecb73e0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007f8ee521dbd0 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7f8ee5312dd0 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
        ap = {{gp_offset = 40, fp_offset = 32654, overflow_arg_area = 0x7f8edecb73f0, reg_save_area = 0x7f8edecb7380}}
        fd = 2
        on_2 = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
#3  0x00007f8ee5223f96 in malloc_printerr (action=3, str=0x7f8ee5312f28 "double free or corruption (fasttop)", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5049
        buf = "00005589ea292750" 
        cp = <optimized out>
        ar_ptr = <optimized out>
        ptr = <optimized out>
        str = 0x7f8ee5312f28 "double free or corruption (fasttop)" 
        action = 3
#4  0x00007f8ee52247de in _int_free (av=0x7f8ee5546b00 <main_arena>, p=0x5589ea292740, have_lock=0) at malloc.c:3905
        size = <optimized out>
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        errstr = <optimized out>
        locked = <optimized out>
        __func__ = "_int_free" 
#5  0x00007f8ee51e2910 in __run_exit_handlers (status=status@entry=1, listp=0x7f8ee55465d8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:83
        atfct = <optimized out>
        onfct = <optimized out>
        cxafct = <optimized out>
        f = <optimized out>
#6  0x00007f8ee51e296a in __GI_exit (status=status@entry=1) at exit.c:105
No locals.
#7  0x00005589e892ecc3 in receiver (interface_for_listening=...) at ./src/netmap_plugin/netmap_collector.cpp:213
        netmap_descriptor = 0x0
        base_nmd = {nr_name = '\000' <repeats 15 times>, nr_version = 0, nr_offset = 0, nr_memsize = 0, nr_tx_slots = 0, nr_rx_slots = 0, nr_tx_rings = 0, nr_rx_rings = 0, nr_ringid = 0, nr_cmd = 0, nr_arg1 = 0, nr_arg2 = 0, nr_arg3 = 0, nr_flags = 0, spare2 = {0}}
        interface = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7f8edecb75b0 "netmap:enp1s0f1"}, _M_string_length = 15, {_M_local_buf = "netmap:enp1s0f1", _M_allocated_capacity = 7294266110230422894}}
        system_interface_name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7f8edecb75d0 "enp1s0f1"}, _M_string_length = 8, {_M_local_buf = "enp1s0f1\000\000\000\000\000\000\000", _M_allocated_capacity = 3559585826791779941}}
        wait_link = <optimized out>
        packet_receiver_thread_group = {threads = {<std::__cxx11::_List_base<boost::thread*, std::allocator<boost::thread*> >> = {_M_impl = {<std::allocator<std::_List_node<boost::thread*> >> = {<__gnu_cxx::new_allocator<std::_List_node<boost::thread*> >> = {<No data fields>}, <No data fields>}, _M_node = {<std::__detail::_List_node_base> = {_M_next = 0x0, _M_prev = 0x0}, _M_storage = {_M_storage = "\000\000\000\000\000\000\000"}}}}, <No data fields>}, m = {state = {shared_count = 0, exclusive = false, upgrade = false, exclusive_waiting_blocked = false}, state_change = {m = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, shared_cond = {internal_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, cond = {__data = {__lock = 0, __futex = 0, __total_seq = 0, __wakeup_seq = 0, __woken_seq = 0, __mutex = 0x0, __nwaiters = 0, __broadcast_seq = 0}, __size = '\000' <repeats 47 times>, __align = 0}}, exclusive_cond = {internal_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, cond = {__data = {__lock = 0, __futex = 0, __total_seq = 0, __wakeup_seq = 0, __woken_seq = 0, __mutex = 0x0, __nwaiters = 0, __broadcast_seq = 0}, __size = '\000' <repeats 47 times>, __align = 0}}, upgrade_cond = {internal_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, cond = {__data = {__lock = 0, __futex = 0, __total_seq = 0, __wakeup_seq = 0, __woken_seq = 0, __mutex = 0x0, __nwaiters = 0, __broadcast_seq = 0}, __size = '\000' <repeats 47 times>, __align = 0}}}}
#8  0x00005589e8931357 in boost::_bi::list1<boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::operator()<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), boost::_bi::list0> (f=<optimized out>, a=<synthetic pointer>..., this=<optimized out>) at /usr/include/boost/bind/bind.hpp:259
No locals.
#9  boost::_bi::bind_t<void, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), boost::_bi::list1<boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::operator() (this=<optimized out>) at /usr/include/boost/bind/bind.hpp:1294
No locals.
#10 boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), boost::_bi::list1<boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::run (this=<optimized out>) at /usr/include/boost/thread/detail/thread.hpp:116
No locals.
#11 0x00007f8ee7fa8116 in boost::(anonymous namespace)::thread_proxy (param=<optimized out>) at libs/thread/src/pthread/thread.cpp:171
        thread_info = {px = 0x7f8ed0000de0, pn = {pi_ = 0x7f8ed0000fd0}}
        lock = <optimized out>
#12 0x00007f8ee6fca494 in start_thread (arg=0x7f8edecb8700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f8edecb8700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140251599963904, 7375924992898153094, 0, 140251616745055, 0, 140251758469184, -7403582275853567354, -7403564522391946618}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread" 
#13 0x00007f8ee5295aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.
```
The causing code in `receiver()` in `src/netmap_plugin/netmap_collector.cpp`:
```c
    if (netmap_descriptor == NULL) {
        logger.error("Can't open netmap device %s", interface.c_str());
        exit(1);
        return;
    }
```

**Comment by pavel-odintsov** [comment]
Hello!

Thank for reporting it! Can you try it?

**Comment by bdrung** [comment]
I cannot test it out. We fixed the configuration (which triggered this code path) and the host is in production now.

**Comment by pavel-odintsov** [comment]
Hello!

I think it should work fine. Bug was pretty silly :(
